apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-test
  template:
    metadata:
      labels:
        app: latency-test
    spec:
      containers:
      - name: latency-test
        image: <your-docker-image>
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: latency-test
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: latency-test
  ports:
  - name: http
    port: 80
    targetPort: 8080
